SELECT 
    A.MOVIE_TITLE 영화제목,
    A.RELEASE_DATE 개봉일,
    A.BOX_OFFICE 수입,
    B.DIR_NAME 감독이름
FROM 
    MOVIE_LIST A,
    DIRECTOR_LIST B
WHERE A.DR_CODE = B.DIR_ID
AND MOVIE_TITLE LIKE '어벤져스%';

SELECT 
    A.MOVIE_TITLE 영화이름,
    B.ACT_CHARACTER 캐릭터이름,
    C.ACT_NAME 영화배우,
    D.GRADE_TITLE 시청나이기준
FROM 
    MOVIE_LIST A,
    CHARACTER_LIST B,
    ACTOR_LIST C,
    GRADE_LIST D
WHERE A.PRO_CODE = B.PRODU_CODE
AND B.ACT_CODE = C.ACT_ID
AND A.GREADE_ID = D.GRADE_ID
AND B.ACT_CHARACTER LIKE '아이언맨';